language: r
sudo: required
notifications:
  email: false
before_install:
  - ./travis-tool.sh bootstrap
  - "cd TestCases"
script:
  - R CMD build ${R_BUILD_ARGS} .
  - R CMD check rcat_0.0.1.tar.gz
  - ./run_tests.R
